### ISSUE TITLE
Serialization of AsyncIterator

### ISSUE THREAD

**Issue by RicherMans** [Element-Research/dataload#4]
I recently came across this problem:
I have a Sequenceloader wrapped around my dataset of multiple speech utterances. One utterance has ~ 500000 samples. Now if I want to wrap a AsyncIterator around the Sequenceloader, I get a reallocation error, which comes from line 19 in Asynciterator:
`local datasetstr = torch.serialize(dataset, "ascii")`

If I change the serialization on both sides to "binary" it works flawlessly. Now my question is, why is the ascii the preferred type and could I maybe pull request that small change to incorporate binary dumps? 

EDIT:
Pull request is here #5

**Comment by nicholas-leonard** [comment]
Yes please send a Pull Request. You could add `serialmode` as an argument to AsyncIterator and give it a default of `ascii`. 

Otherwise, I fail to see why you would gain any performance advantage from decorating SequenceLoader with AsyncIterator. The latter should be used for ImageClass as it is blocks when loading images from disk.
